### ISSUE TITLE
Extend on page history list beyond changes in URL after # 

### ISSUE THREAD

**Issue by deysonali** [aquanauts/terrain#14]
- Find a way to deal with overall URL changes, changes in host etc.

**Comment by benrady-aq** [comment]
You can store the session ID, URL history, and hash history, in the [sessionStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage) object.

If the session storage already contains a session ID, use it. Otherwise get a new session ID from `window.__terrainSessionID` and store it in local storage.

Similarly, whenever the page is loaded, you can add or append the current `window.location.href`.
